<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_NumericValue" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_NumericValueInputMapping" Comment="" x="1053.33" y="926.67">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="NumberVariable_Gesamtziel" Comment=""/>
			<Parameter Name="NumericValueInput_1" Value="'Counter.GesamtzaehlerVergleich.IN_NumberVariable'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="NumberVariable_Tagesziel" Comment=""/>
			<Parameter Name="NumericValueInput_2" Value="'Counter.TageszaehlerVergleich.IN_NumberVariable'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" Comment="" dx1="73.33" dx2="73.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
