<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ZaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Counter::subs::Zaehler">
		<Import declaration="FBs::Counter::const::DefaultPool::OutputString_ZielErreicht"/>
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="u16ObjId_Ziel" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_Pointer" Type="UINT"/>
		</InputVars>
		<Sockets>
			<AdapterDeclaration Name="CV" Type="adapter::types::unidirectional::AUDI" Comment="Counter Value"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Ziel_erreicht" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="7100" y="-1100">
		</FB>
		<FB Name="F_GE" Type="iec61131::comparison::AUDI_GE" x="2660" y="-660">
		</FB>
		<FB Name="NVS_UDINT" Type="logiBUS::storage::esp32_nvs::NVS_AUDI" x="5060" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue_Ziel" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="9400" y="900">
		</FB>
		<FB Name="AX_SEL" Type="adapter::iec61131::selection::AX_SEL_AUDI" x="4600" y="-1100">
			<Parameter Name="IN0" Value="ID_NULL"/>
			<Parameter Name="IN1" Value="OutputString_ZielErreicht"/>
		</FB>
		<FB Name="IN_NumberVariable" Type="isobus::UT::io::NumericValue::NumericValue_IDA" x="700" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AD_TO_AUDI" Type="adapter::conversion::unidirectional::AD_TO_AUDI" x="3060" y="1200">
		</FB>
		<FB Name="AUDI_SPLIT_2" Type="adapter::events::unidirectional::AUDI_SPLIT_2" x="7200" y="1200">
		</FB>
		<DataConnections>
			<Connection Source="u16ObjId_Pointer" Destination="Q_NumericValue_Ziel_erreicht.u16ObjId" dx1="4066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId_Ziel" Destination="Q_NumericValue_Ziel.u16ObjId" dx1="5273.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_UDINT.KEY" dx1="3253.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId_Ziel" Destination="IN_NumberVariable.u16ObjId" dx1="1426.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="F_GE.OUT" Destination="AX_SEL.G" dx1="700"/>
			<Connection Source="AX_SEL.OUT" Destination="Q_NumericValue_Ziel_erreicht.u32NewValue"/>
			<Connection Source="IN_NumberVariable.IN" Destination="AD_TO_AUDI.AD_IN" dx1="220"/>
			<Connection Source="AD_TO_AUDI.AUDI_OUT" Destination="NVS_UDINT.AUDI_IN" dx1="593.33"/>
			<Connection Source="AUDI_SPLIT_2.OUT2" Destination="Q_NumericValue_Ziel.u32NewValue" dx1="760"/>
			<Connection Source="NVS_UDINT.AUDI_OUT" Destination="AUDI_SPLIT_2.IN" dx1="493.33"/>
			<Connection Source="CV" Destination="F_GE.IN1" dx1="2253.33"/>
			<Connection Source="AUDI_SPLIT_2.OUT1" Destination="F_GE.IN2" dx1="80" dx2="80" dy="-826.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
