<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Zaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Counter::subs::Zaehler">
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="CV" Type="adapter::types::unidirectional::AUDI" Comment="Counter Value"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="CU" Type="adapter::types::unidirectional::AX" Comment="Count Up"/>
			<AdapterDeclaration Name="CD" Type="adapter::types::unidirectional::AX" Comment="Count Down"/>
			<AdapterDeclaration Name="R" Type="adapter::types::unidirectional::AX" Comment="Reset"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AUDI_FB_CTUD" Type="adapter::iec61131::counters::AUDI_FB_CTUD" x="100" y="1100">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue_AUDI" x="5500" y="900">
		</FB>
		<FB Name="NVS_AUDI" Type="logiBUS::storage::esp32_nvs::NVS_AUDI" x="4133.33" y="2366.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="AUDI_SPLIT_3" Type="adapter::events::unidirectional::AUDI_SPLIT_3" x="1900" y="1400">
		</FB>
		<SubApp Name="LD_helper" Type="FBs::Counter::subs::Zaehler::LD_helper" x="-1800" y="1800">
		</SubApp>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_NumericValue.u16ObjId" dx1="2840">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_AUDI.KEY" dx1="2226.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AUDI_FB_CTUD.CV" Destination="AUDI_SPLIT_3.IN" dx1="193.33"/>
			<Connection Source="AUDI_SPLIT_3.OUT1" Destination="CV" dx1="886.67"/>
			<Connection Source="AUDI_SPLIT_3.OUT2" Destination="Q_NumericValue.u32NewValue" dx1="1373.33"/>
			<Connection Source="AUDI_SPLIT_3.OUT3" Destination="NVS_AUDI.AUDI_IN" dx1="693.33"/>
			<Connection Source="CU" Destination="AUDI_FB_CTUD.CU" dx1="840"/>
			<Connection Source="CD" Destination="AUDI_FB_CTUD.CD" dx1="700"/>
			<Connection Source="R" Destination="AUDI_FB_CTUD.R" dx1="586.67"/>
			<Connection Source="NVS_AUDI.AUDI_OUT" Destination="LD_helper.IN" dx1="633.33" dx2="80" dy="433.33"/>
			<Connection Source="LD_helper.OUT" Destination="AUDI_FB_CTUD.PV" dx1="886.67"/>
			<Connection Source="LD_helper.Q" Destination="AUDI_FB_CTUD.LD" dx1="726.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
