<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ZaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
			<VarDeclaration Name="KEY" Type="STRING"/>
			<VarDeclaration Name="u16ObjId_Ziel" Type="UINT"/>
			<VarDeclaration Name="u16ObjId_Pointer" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Ziel_erreicht" Type="Q_NumericValue" x="7066.67" y="-933.33">
		</FB>
		<FB Name="F_GE" Type="iec61131::comparison::F_GE" x="2660" y="-660">
		</FB>
		<FB Name="NVS_UDINT" Type="NVS" x="5060" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue_Ziel" Type="Q_NumericValue" x="9200" y="926.67">
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="4520" y="-520">
			<Parameter Name="IN0" Value="isobus::ID_NULL"/>
			<Parameter Name="IN1" Value="DefaultPool::OutputString_ZielErreicht"/>
		</FB>
		<FB Name="IN_NumberVariable" Type="eclipse4diac::io::ID" x="1600" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="3060" y="1200">
		</FB>
		<FB Name="F_MOVE" Type="iec61131::arithmetic::F_MOVE" x="800" y="-200">
			<Attribute Name="DataType" Value="UDINT"/>
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<EventConnections>
			<Connection Source="REQ" Destination="F_GE.REQ" dx1="660"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" dx1="700"/>
			<Connection Source="IN_NumberVariable.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="220"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Ziel_erreicht.REQ" dx1="340"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Ziel.REQ" dx1="7560"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS_UDINT.SET" dx1="480"/>
			<Connection Source="NVS_UDINT.INITO" Destination="NVS_UDINT.GET" dx1="300" dx2="300" dy="-300"/>
			<Connection Source="NVS_UDINT.GETO" Destination="Q_NumericValue_Ziel.REQ" dx1="760"/>
			<Connection Source="NVS_UDINT.SETO" Destination="F_MOVE.REQ" dx1="360" dx2="360" dy="-520"/>
			<Connection Source="NVS_UDINT.GETO" Destination="F_MOVE.REQ" dx1="460" dx2="460" dy="-740"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" dx1="333.33"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" dx1="700"/>
			<Connection Source="IN_NumberVariable.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="220"/>
			<Connection Source="u16ObjId_Pointer" Destination="Q_NumericValue_Ziel_erreicht.u16ObjId" dx1="4066.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Ziel_erreicht.u32NewValue" dx1="820"/>
			<Connection Source="u16ObjId_Ziel" Destination="Q_NumericValue_Ziel.u16ObjId" dx1="5273.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_UDINT.KEY" dx1="3253.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS_UDINT.VALUE" dx1="486.67"/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="Q_NumericValue_Ziel.u32NewValue" dx1="760"/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="F_MOVE.IN" dx1="566.67" dx2="566.67" dy="-1280"/>
			<Connection Source="F_MOVE.OUT" Destination="F_GE.IN2" dx1="646.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
