<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ZaehlerVergleich" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-18">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
			<VarDeclaration Name="KEY" Type="STRING" Comment=""/>
			<VarDeclaration Name="u16ObjId_Ziel" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjId_Pointer" Type="UINT" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue_Ziel_erreicht" Type="Q_NumericValue" Comment="" x="7066.67" y="-933.33">
		</FB>
		<FB Name="F_GE" Type="F_GE" Comment="" x="2660" y="-660">
		</FB>
		<FB Name="NVS_UDINT" Type="NVS" Comment="" x="5060" y="800">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="Q_NumericValue_Ziel" Type="Q_NumericValue" Comment="" x="9200" y="926.67">
		</FB>
		<FB Name="F_SEL" Type="F_SEL" Comment="" x="4520" y="-520">
			<Parameter Name="IN0" Value="ID_NULL" Comment=""/>
			<Parameter Name="IN1" Value="OutputString_ZielErreicht" Comment=""/>
		</FB>
		<FB Name="IN_NumberVariable" Type="ID" Comment="" x="1600" y="1200">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="F_DWORD_TO_UDINT" Comment="" x="3060" y="1200">
		</FB>
		<FB Name="F_MOVE" Type="F_MOVE" Comment="" x="800" y="-200">
			<Attribute Name="DataType" Value="UDINT"/>
		</FB>
		<EventConnections>
			<Connection Source="REQ" Destination="F_GE.REQ" Comment="" dx1="660"/>
			<Connection Source="F_GE.CNF" Destination="F_SEL.REQ" Comment="" dx1="700" dx2="700" dy="0"/>
			<Connection Source="INIT" Destination="IN_NumberVariable.INIT" Comment="" dx1="80"/>
			<Connection Source="IN_NumberVariable.IND" Destination="F_DWORD_TO_UDINT.REQ" Comment="" dx1="220"/>
			<Connection Source="INIT" Destination="Q_NumericValue_Ziel_erreicht.INIT" Comment="" dx1="4520" dx2="4520" dy="0"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue_Ziel_erreicht.REQ" Comment="" dx1="340" dx2="340" dy="0"/>
			<Connection Source="INIT" Destination="Q_NumericValue_Ziel.INIT" Comment="" dx1="7700" dx2="7700" dy="0"/>
			<Connection Source="rVT" Destination="Q_NumericValue_Ziel.REQ" Comment="" dx1="7560" dx2="7560" dy="0"/>
			<Connection Source="INIT" Destination="NVS_UDINT.INIT" Comment="" dx1="80" dx2="80" dy="0"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="NVS_UDINT.SET" Comment="" dx1="480" dx2="480" dy="0"/>
			<Connection Source="NVS_UDINT.INITO" Destination="NVS_UDINT.GET" Comment="" dx1="300" dx2="300" dy="-300"/>
			<Connection Source="NVS_UDINT.GETO" Destination="Q_NumericValue_Ziel.REQ" Comment="" dx1="760" dx2="760" dy="0"/>
			<Connection Source="NVS_UDINT.SETO" Destination="F_MOVE.REQ" Comment="" dx1="360" dx2="360" dy="-520"/>
			<Connection Source="NVS_UDINT.GETO" Destination="F_MOVE.REQ" Comment="" dx1="460" dx2="273.33" dy="-740"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CV" Destination="F_GE.IN1" Comment="" dx1="333.33"/>
			<Connection Source="F_GE.OUT" Destination="F_SEL.G" Comment="" dx1="700" dx2="700" dy="0"/>
			<Connection Source="IN_NumberVariable.IN" Destination="F_DWORD_TO_UDINT.IN" Comment="" dx1="220"/>
			<Connection Source="u16ObjId_Pointer" Destination="Q_NumericValue_Ziel_erreicht.u16ObjId" Comment="" dx1="4066.67" dx2="4066.67" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue_Ziel_erreicht.u32NewValue" Comment="" dx1="820" dx2="820" dy="0"/>
			<Connection Source="u16ObjId_Ziel" Destination="Q_NumericValue_Ziel.u16ObjId" Comment="" dx1="5273.33" dx2="5273.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_UDINT.KEY" Comment="" dx1="3253.33" dx2="3253.33" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="NVS_UDINT.VALUE" Comment="" dx1="486.67" dx2="486.67" dy="0"/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="Q_NumericValue_Ziel.u32NewValue" Comment="" dx1="760" dx2="760" dy="0"/>
			<Connection Source="NVS_UDINT.VALUEO" Destination="F_MOVE.IN" Comment="" dx1="566.67" dx2="186.67" dy="-1280"/>
			<Connection Source="F_MOVE.OUT" Destination="F_GE.IN2" Comment="" dx1="646.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
