<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Zaehler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="CU" Type="Event" Comment="Count Up">
			</SubAppEvent>
			<SubAppEvent Name="CD" Type="Event" Comment="Count Down">
			</SubAppEvent>
			<SubAppEvent Name="R" Type="Event" Comment="Reset">
			</SubAppEvent>
			<SubAppEvent Name="rVT" Type="Event" Comment="refresh VT">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="Confirmation -- Counter Value was changed">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="KEY" Type="STRING" Comment=""/>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="CV" Type="UDINT" Comment="Counter Value"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_CTUD_UDINT" Type="E_CTUD_UDINT" Comment="" x="400.0" y="400.0">
		</FB>
		<FB Name="Q_NumericValue" Type="Q_NumericValue" Comment="" x="4266.666666666667" y="933.3333333333334">
		</FB>
		<FB Name="NVS_UDINT" Type="NVS_UDINT" Comment="" x="2933.3333333333335" y="2266.666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_NumericValue.INIT" Comment="" dx1="4050.0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ" Comment="" dx1="75.0"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="Q_NumericValue.REQ" Comment="" dx1="75.0"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="Q_NumericValue.REQ" Comment="" dx1="75.0"/>
			<Connection Source="CU" Destination="E_CTUD_UDINT.CU" Comment="" dx1="883.3333333333334"/>
			<Connection Source="CD" Destination="E_CTUD_UDINT.CD" Comment="" dx1="775.0"/>
			<Connection Source="R" Destination="E_CTUD_UDINT.R" Comment="" dx1="791.6666666666667"/>
			<Connection Source="INIT" Destination="NVS_UDINT.INIT" Comment="" dx1="4050.0"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="NVS_UDINT.SET" Comment="" dx1="400.0"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="NVS_UDINT.SET" Comment="" dx1="300.0"/>
			<Connection Source="NVS_UDINT.INITO" Destination="NVS_UDINT.GET" Comment="" dx1="266.6666666666667" dx2="583.3333333333334" dy="-191.66666666666669"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="CNF" Comment="" dx1="2600.0"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="CNF" Comment="" dx1="2600.0"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="CNF" Comment="" dx1="2600.0"/>
			<Connection Source="rVT" Destination="Q_NumericValue.REQ" Comment="" dx1="3666.666666666667"/>
			<Connection Source="rVT" Destination="CNF" Comment="" dx1="7600.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" Comment="" dx1="616.6666666666667"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="NVS_UDINT.VALUE" Comment="" dx1="191.66666666666669"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="CV" Comment="" dx1="166.66666666666669"/>
			<Connection Source="u16ObjId" Destination="Q_NumericValue.u16ObjId" Comment="" dx1="2833.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="KEY" Destination="NVS_UDINT.KEY" Comment="" dx1="2225.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
