<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="VT_active" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-19">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_D_FF" Type="iec61499::events::E_D_FF" x="2266.67" y="133.33">
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="0" y="-133.33">
		</FB>
		<EventConnections>
			<Connection Source="E_D_FF.EO" Destination="EO" dx1="980"/>
			<Connection Source="CbVtStatus.IND" Destination="E_D_FF.CLK" dx1="1420"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CbVtStatus.qWsActive" Destination="E_D_FF.D" dx1="753.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
