<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_aux" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_AuxiliaryInputMapping" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" x="-1600" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::AuxFunction2_PlusPlus"/>
			<Parameter Name="DigitalInput_1" Value="'App.Counter.func.PlusPlus.AuxFunction2'"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::AuxFunction2_MinusMinus"/>
			<Parameter Name="DigitalInput_2" Value="'App.Counter.func.MinusMinus.AuxFunction2'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
