<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" x="1066.67" y="933.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::SoftKey_PlusPlus"/>
			<Parameter Name="DigitalInput_1" Value="'App.Counter.func.PlusPlus.SoftKey'"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::SoftKey_Reset_Gesamtzaehler"/>
			<Parameter Name="DigitalInput_2" Value="'App.Counter.func.Reset_Gesamtzaehler.SoftKey'"/>
			<Parameter Name="u16ObjId_3" Value="DefaultPool::SoftKey_Reset_Tageszaehler"/>
			<Parameter Name="DigitalInput_3" Value="'App.Counter.func.Reset_Tageszaehler.SoftKey'"/>
			<Parameter Name="u16ObjId_4" Value="DefaultPool::SoftKey_MinusMinus"/>
			<Parameter Name="DigitalInput_4" Value="'App.Counter.func.MinusMinus.SoftKey'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
