<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Tuple" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button" Type="IE" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey" Type="IE" x="0" y="933.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxFunction2" Type="IX" x="133.33" y="1866.67">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="1466.67" y="2000">
		</FB>
		<EventConnections>
			<Connection Source="Button.IND" Destination="IND" dx1="1566.67"/>
			<Connection Source="SoftKey.IND" Destination="IND" dx1="1626.67"/>
			<Connection Source="AuxFunction2.IND" Destination="E_SWITCH.EI" dx1="113.33"/>
			<Connection Source="E_SWITCH.EO0" Destination="IND" dx1="826.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AuxFunction2.IN" Destination="E_SWITCH.G" dx1="320"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
