<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Counter" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="DefaultPool::AuxFunction2_MinusMinus"/>
		<Import declaration="DefaultPool::AuxFunction2_PlusPlus"/>
		<Import declaration="DefaultPool::Button_MinusMinus"/>
		<Import declaration="DefaultPool::Button_NextVT"/>
		<Import declaration="DefaultPool::Button_PlusPlus"/>
		<Import declaration="DefaultPool::Button_Reset_Gesamtzaehler"/>
		<Import declaration="DefaultPool::Button_Reset_Tageszaehler"/>
		<Import declaration="DefaultPool::NumberVariable_Gesamtzaehler"/>
		<Import declaration="DefaultPool::NumberVariable_Gesamtziel"/>
		<Import declaration="DefaultPool::NumberVariable_Tageszaehler"/>
		<Import declaration="DefaultPool::NumberVariable_Tagesziel"/>
		<Import declaration="DefaultPool::ObjectPointer_Gesamtziel"/>
		<Import declaration="DefaultPool::ObjectPointer_Tagesziel"/>
		<Import declaration="DefaultPool::SoftKey_MinusMinus"/>
		<Import declaration="DefaultPool::SoftKey_PlusPlus"/>
		<Import declaration="DefaultPool::SoftKey_Reset_Gesamtzaehler"/>
		<Import declaration="DefaultPool::SoftKey_Reset_Tageszaehler"/>
		<Import declaration="NVS_Keys::KEY_GESAMTZAEHLER"/>
		<Import declaration="NVS_Keys::KEY_GESAMTZIEL"/>
		<Import declaration="NVS_Keys::KEY_TAGESZAEHLER"/>
		<Import declaration="NVS_Keys::KEY_TAGESZIEL"/>
		<Import declaration="isobus::UT::io::Button::ButtonActivationCode::BT_RELEASED_UNLATCHED"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="MinusMinus" Type="FBs::Counter::subs::Buttons::Tuple" x="-106.67" y="-1200">
			<Parameter Name="u16ObjId_BT" Value="Button_MinusMinus"/>
			<Parameter Name="u16ObjId_SK" Value="SoftKey_MinusMinus"/>
			<Parameter Name="u16ObjId_AUX" Value="AuxFunction2_MinusMinus"/>
		</SubApp>
		<SubApp Name="PlusPlus" Type="FBs::Counter::subs::Buttons::Tuple" x="-106.67" y="-2000">
			<Parameter Name="u16ObjId_BT" Value="Button_PlusPlus"/>
			<Parameter Name="u16ObjId_SK" Value="SoftKey_PlusPlus"/>
			<Parameter Name="u16ObjId_AUX" Value="AuxFunction2_PlusPlus"/>
		</SubApp>
		<SubApp Name="Reset_Gesamtzaehler" Type="FBs::Counter::subs::Buttons::Reset" x="-400" y="-200">
			<Parameter Name="u16ObjId_BT" Value="Button_Reset_Gesamtzaehler"/>
			<Parameter Name="u16ObjId_SK" Value="SoftKey_Reset_Gesamtzaehler"/>
		</SubApp>
		<SubApp Name="Reset_Tageszaehler" Type="FBs::Counter::subs::Buttons::Reset" x="-400" y="400">
			<Parameter Name="u16ObjId_BT" Value="Button_Reset_Tageszaehler"/>
			<Parameter Name="u16ObjId_SK" Value="SoftKey_Reset_Tageszaehler"/>
		</SubApp>
		<SubApp Name="Gesamtzaehler" Type="FBs::Counter::subs::Zaehler::Zaehler" x="4000" y="-2000">
			<Parameter Name="KEY" Value="KEY_GESAMTZAEHLER"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_Gesamtzaehler"/>
		</SubApp>
		<SubApp Name="Tageszaehler" Type="FBs::Counter::subs::Zaehler::Zaehler" x="4000" y="0">
			<Parameter Name="KEY" Value="KEY_TAGESZAEHLER"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_Tageszaehler"/>
		</SubApp>
		<SubApp Name="TageszaehlerVergleich" Type="FBs::Counter::subs::Zaehler::ZaehlerVergleich" x="7100" y="0">
			<Parameter Name="KEY" Value="KEY_TAGESZIEL"/>
			<Parameter Name="u16ObjId_Ziel" Value="NumberVariable_Tagesziel"/>
			<Parameter Name="u16ObjId_Pointer" Value="ObjectPointer_Tagesziel"/>
		</SubApp>
		<SubApp Name="GesamtzaehlerVergleich" Type="FBs::Counter::subs::Zaehler::ZaehlerVergleich" x="7100" y="-2000">
			<Parameter Name="KEY" Value="KEY_GESAMTZIEL"/>
			<Parameter Name="u16ObjId_Ziel" Value="NumberVariable_Gesamtziel"/>
			<Parameter Name="u16ObjId_Pointer" Value="ObjectPointer_Gesamtziel"/>
		</SubApp>
		<FB Name="NextVT" Type="isobus::UT::util::NextVT" x="2100" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Button" Type="isobus::UT::io::Button::Button_IE" x="-300" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_NextVT"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<EventConnections>
			<Connection Source="PlusPlus.IND" Destination="Gesamtzaehler.CU"/>
			<Connection Source="MinusMinus.IND" Destination="Gesamtzaehler.CD" dx1="1740"/>
			<Connection Source="Reset_Gesamtzaehler.IND" Destination="Gesamtzaehler.R" dx1="2186.67"/>
			<Connection Source="PlusPlus.IND" Destination="Tageszaehler.CU" dx1="1026.67"/>
			<Connection Source="MinusMinus.IND" Destination="Tageszaehler.CD" dx1="1740"/>
			<Connection Source="Reset_Tageszaehler.IND" Destination="Tageszaehler.R" dx1="1326.67"/>
			<Connection Source="Tageszaehler.CNF" Destination="TageszaehlerVergleich.REQ"/>
			<Connection Source="Gesamtzaehler.CNF" Destination="GesamtzaehlerVergleich.REQ"/>
			<Connection Source="Button.IND" Destination="NextVT.REQ" dx1="753.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Tageszaehler.CV" Destination="TageszaehlerVergleich.CV" dx1="506.67"/>
			<Connection Source="Gesamtzaehler.CV" Destination="GesamtzaehlerVergleich.CV" dx1="480"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
