<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Reset" Comment="1 Button, 1 Softkey">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Counter::subs::Buttons">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId_BT" Type="UINT" Comment="Object ID Button" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjId_SK" Type="UINT" Comment="Object ID SoftKey" InitialValue="ID_NULL"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button" Type="isobus::UT::io::Button::Button_IXA" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey" Type="isobus::UT::io::Softkey::Softkey_IXA" x="0" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_XOR_2" Type="adapter::booleanOperators::AX_XOR_2" x="2700" y="900">
		</FB>
		<DataConnections>
			<Connection Source="u16ObjId_BT" Destination="Button.u16ObjId" dx1="1226.67"/>
			<Connection Source="u16ObjId_SK" Destination="SoftKey.u16ObjId" dx1="800"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="Button.IN" Destination="AX_XOR_2.IN1" dx1="906.67"/>
			<Connection Source="SoftKey.IN" Destination="AX_XOR_2.IN2" dx1="906.67"/>
			<Connection Source="AX_XOR_2.OUT" Destination="IN" dx1="866.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
