<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Tuple" Comment="1 Button, 1 Softkey, 1 Aux">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-02-17">
	</VersionInfo>
	<CompilerInfo packageName="FBs::Counter::subs::Buttons">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId_BT" Type="UINT" Comment="Object ID Button" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjId_SK" Type="UINT" Comment="Object ID SoftKey" InitialValue="ID_NULL"/>
			<VarDeclaration Name="u16ObjId_AUX" Type="UINT" Comment="Object ID Aux" InitialValue="ID_NULL"/>
		</InputVars>
		<Plugs>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Button" Type="isobus::UT::io::Button::Button_IXA" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey" Type="isobus::UT::io::Softkey::Softkey_IXA" x="0" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxFunction2" Type="isobus::UT::io::Auxiliary::IN::Aux_IXA" x="0" y="2200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AX_XOR_3" Type="adapter::booleanOperators::AX_XOR_3" x="4200" y="1000">
		</FB>
		<DataConnections>
			<Connection Source="u16ObjId_BT" Destination="Button.u16ObjId" dx1="1406.67"/>
			<Connection Source="u16ObjId_SK" Destination="SoftKey.u16ObjId" dx1="1040"/>
			<Connection Source="u16ObjId_AUX" Destination="AuxFunction2.u16ObjId" dx1="633.33"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="AX_XOR_3.OUT" Destination="IN" dx1="1413.33"/>
			<Connection Source="Button.IN" Destination="AX_XOR_3.IN1" dx1="1700"/>
			<Connection Source="SoftKey.IN" Destination="AX_XOR_3.IN2" dx1="1700"/>
			<Connection Source="AuxFunction2.IN" Destination="AX_XOR_3.IN3" dx1="2066.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
